### ISSUE TITLE
Immutability chapter in ARCHITECTURE.md

### ISSUE THREAD

**Issue by xabbu42** [maplibre/maplibre-gl-native#136]
As i interpret that chapter, all ::Impl classes in mapbox and therefore also in the maplibre fork should be immutable by design. But the commit d62ff400c6f75750d71b563344b1ca1e07b9b576 breaks with that as it adds setResourceOptions to most ::Impl classes of file sources. 

I'm not sure if this is new or if there already are mutable ::Impl classes which I did not see.

I see the following possibilities:

* I read that chapter wrong. In that case perhaps we can make it clearer?
* That chapter was right for mapbox, but we no longer abide by that design. In that case we should also change the documentation.
* That chapter and my reading are correct and still applicable. In that case the code should be fixed.

**Comment by xabbu42** [comment]
It seems there are other already existing instances of mutability in the changed implementation classes. What triped me up particularly was the following quote from ARCHITECTURE.md:

> Immutability is core to the implementation, and yet one of the defining features of Mapbox GL is the ability to manipulate and mutate the style freely at runtime. How can this be possible if everything is immutable? The answer turns on the distinction mentioned in the previous section between public classes such as Layer and private implementations such as Layer::Impl. In Mapbox GL, the latter is immutable, but the former is not:

Perhaps we could make it more explicit that only the listed implementations are immutable and that does not hold for all implementation classes?

**Comment by petr-pokorny-1** [comment]
I would agree to follow the original Mapbox design where possible. But in those changes you mentioned I decided to implement set methods for the following reasons:

1. I have noticed that there are some methods which are mutating ::Impl classes (for example [setResourceTransform](https://github.com/maplibre/maplibre-gl-native/blob/8b804a19038c6f5ed01261f0bb4364cc7e386e4a/platform/default/src/mbgl/storage/online_file_source.cpp#L327) in OnlineFileSource::Impl). 
2. The configuration methods (such as setApiKey and setAPIBaseURL) are also mutating the OnlineFileSource::Impl instance rather than cloning and replacing immutable ::impl class. So I though the extended configuration functionality should follow that.
3. Since the use case for configuring backend API URL, ApiKey etc is used rarely and typically happens at startup, i thought that for the performance reasons, it is better to add set* methods rather than creating clones of ::Impl instances, set all the configuration options and then replace all original ones. The thread safety in set methods is ensured by cloning the options object.

However having said that I like you are reviewing these changes! And I'd be glad to make it better. Please free to submit PR if you have any ides for improvements.

**Comment by xabbu42** [comment]
I now think your changes are in line with the original mapbox design, as the chapter actually carefully avoids saying anywhere that all implementations are immutable. the most ambiguous section is the one I quoted above. I will try to make a pull request to make the documentation clearer, but english ist not my first language.
