### ISSUE TITLE
Offline MBTiles support?

### ISSUE THREAD

**Issue by carlos-mg89** [maplibre/maplibre-gl-native#17]
I haven't been able to find in the repository and/or documentation if there's support for offline vector (and raster too) MBTiles?

I admit I don't know if that was possible in the original Mapbox implementation, so if it wasn't there, it's quite likely it isn't in this project at the moment.

Aside from this, is there any documentation for how to use the library? So far I've seen how to set it up, but not how to interact with it. E.g.: add markers, draw paths, etc.

Thank you in advance and apologies if this isn't the proper place where to ask about this. I'd more than happy to move this question somewhere else.

**Comment by roblabs** [comment]
Support for other protocols besides `https` are _in the code_, but I agree it could use some upgrades in the documentation.  Pull requests for documentation and test samples are welcome.  

Protocols `asset://`, `file://`, and `mbtiles://` are listed in the MapLibre code.  `mbtiles://` is new to MapLibre since its donation by MapTiler.  The asset and file protocols were in Mapbox GL native.

https://github.com/maplibre/maplibre-gl-native/blob/cd8d56467962cfb4c99418b0226d9ea2adb48c30/include/mbgl/util/constants.hpp#L62-L65

---

Here is a list of published apps which mention using MapLibre.  A future Wiki should list the published apps that make use MapLibre.

* [roblabs/openmaptiles-ios-demo][roblabs/openmaptiles-ios-demo]
* by Klokan Technologies GmbH
  * [MapTiler Mobile for Android][MapTiler Mobile for Android]
  * [OpenMapTiles for Android][OpenMapTiles for Android]
  * [MapTiler Mobil‪e for iOS][MapTiler Mobil‪e for iOS]

[roblabs/openmaptiles-ios-demo]: https://github.com/roblabs/openmaptiles-ios-demo
[MapTiler Mobile for Android]: https://play.google.com/store/apps/details?id=com.maptiler.geoeditor
[OpenMapTiles for Android]: https://play.google.com/store/apps/details?id=com.klokantech.osm2vectortiles
[MapTiler Mobil‪e for iOS]: https://apps.apple.com/us/app/geoeditor-for-maptiler/id1168561747

**Comment by carlos-mg89** [comment]
Thanks for the info @roblabs I'd definitely give it a try!

**Comment by SpeedFire0** [comment]
> So far I've seen how to set it up, but not how to interact with it. E.g.: add markers, draw paths, etc.

Hi, can you please share how you were able to set it up? Is there any documentation?

**Comment by typebrook** [comment]
> So far I've seen how to set it up, but not how to interact with it. E.g.: add markers, draw paths, etc.

@SpeedFire0 
I have my first try on mbtiles protocol yesterday, and it works fine.
Here is my related code (maybe it is not clear):
https://github.com/typebrook/mapstew-android/blob/3c6190b401/app/src/main/java/io/typebrook/mapstew/map/MaplibreFragment.kt#L125

Anyway, the format for each mbtiles source should be looks like:
```json
{
  "id": "mbtilesSource",
  "tiles": [
    "mbtiles://{PATH_TO_YOUR_MBTILES}
  ]
}
```

In my case, I put mbtiles in my app's interal storage for database. So `PATH_TO_YOUR_MBTILES` is `context.getDatabasePath("test.mbtiles")`

**Comment by tir38** [comment]
Am I right to understand that this is for shipping tiles with an apk. This is not about downloading tiles in-app and using later when offline as in [this sample](https://github.com/mapbox/mapbox-gl-native-android/blob/6db4db9fffb7a696feb92438fa4bb6b21b65d117/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/offline/OfflineActivity.java)?
