### ISSUE TITLE
Attribution not working in iOS sdk

### ISSUE THREAD

**Issue by d3mon187** [maplibre/maplibre-gl-native#183]
I built a simple demo app and noticed that on the iOS version I don't have any attribution text or links in the information popup.  Just shows the text for "Maplibre Maps SDK for iOS".  Was this broken, or does iOS require extra code to enable it?  I did try simplifying the attribution field in my style.json, but it doesn't seem like there is an issue there.

**Comment by atierian** [comment]
I noticed the same issue. 

Based on [this](https://github.com/maplibre/maplibre-gl-native/blob/d28e4a040fe22ef42cf23259b165ef726d550253/platform/ios/platform/ios/src/MGLMapView.mm#L2746-L2780), it looks like the attribution text is just being set to the localized string `SDK_NAME`, which is "MapLibre Maps SDK for iOS" for English. I would expect that the MGLMapView pulls the attribution information from the style's source leveraging `MGLVectorTileSource().attributionInfos`.

Could someone confirm that pulling attribution info from the source is expected behavior? If so, I'll try to work on a fix.
