### ISSUE TITLE
Adding post-fork Mapbox features

### ISSUE THREAD

**Issue by tir38** [maplibre/maplibre-gl-native#233]
_Getting access to your Slack channel is a nightmare. So I'm asking here._

What is the process for adding new features to Maplibre that correspond to changes that Mapbox made after the Maplibre fork? Can I just port them over as a new PR?

**Comment by wipfli** [comment]
Thanks for asking. Porting features from Mapbox only works if the source license allows it. In Mapbox GL JS v2, e.g., the license does not allow porting code to MapLibre GL JS. 

Which features are you thinking of?

**Comment by tir38** [comment]
Many things sadly =( Is there guidance on how to add new features to maplibre that might exist in mapbox w/out violating license?

**Comment by wipfli** [comment]
We had discussions on not violating licenses in the context of the terrain3d pull request im MapLibre GL JS. Our approach there was to not look at the implementation of other companies at all. To give an example, say you like the globe view that some map products show when zooming out. You are free to implement this yourself in MapLibre and no one we be able to claim that this is a license violation, since globe view is just a concept which is not under copyright. Don't know if this helps... Maybe someone who actually already received cease and desist letters could share better insights... @nyurik @klokan maybe?

**Comment by wipfli** [comment]
@tir38 see also this discussion we had in MapLibre GL JS: https://github.com/maplibre/maplibre-gl-js/discussions/701

**Comment by wipfli** [comment]
@tir38 let me close this issue for the time being. Feel free reopen and to ask any question regarding licensing and implementing missing features...
