### ISSUE TITLE
Building on Linux

### ISSUE THREAD

**Issue by dwoznicki** [maplibre/maplibre-gl-native#280]
I'm trying to create bindings to rasterize vector tiles to images from within my Java application, but first I need to build the maplibre-gl-native library on my Debian machine. I tried following the steps [in the Linux platform README](https://github.com/maplibre/maplibre-gl-native/tree/main/platform/linux), but ran into some issues.

1. I don't have a MAPBOX_ACCESS_TOKEN. Is this still necessary?
2. When I run `make glfw-app`, I get the following message

```
make: *** No rule to make target 'glfw-app'.  Stop.
```

I suspect these instructions are out of date, but I'm not sure what to do instead.

Does anyone have any advice for building on Linux? I'm not at all familiar with C++ development, so explaining otherwise obvious steps would be very appreciated.

**Comment by acalcutt** [comment]
Based on the [node build](https://github.com/maplibre/maplibre-gl-native/blob/main/.github/workflows/node-ci.yml) and [CMakeLists.txt](https://github.com/maplibre/maplibre-gl-native/blob/main/CMakeLists.txt), it looks like the commands are something like

```
apt-get install -y ccache cmake ninja-build pkg-config xvfb libcurl4-openssl-dev libglfw3-dev libuv1-dev g++-10 libc++-9-dev libc++abi-9-dev

cmake . -B build -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10

cmake --build build -j $(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null)
```

If I'm reading https://github.com/maplibre/maplibre-gl-native/blob/main/CMakeLists.txt#L1052-L1064 correctly, if you don't specify the MBGL_WITH_QT (-DMBGL_WITH_QT=ON), and your build system is linux, it is going to build what's in /platform/linux/linux.cmake

Just a side note, I did try to build it with -DMBGL_WITH_QT=ON , but it would not work until I added 
`SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread") `
to CMakeLists.txt (around line 88 with the other sets)

**Comment by brendan-ward** [comment]
@dwoznicki in case it helps as a reference point, I built a rasterizer using a C++ wrapper for use in Python: [pymgl](https://github.com/brendan-ward/pymgl).

I ended up using custom CMake files to assist with building the core parts of maplibre-gl-native that I needed:
* https://github.com/brendan-ward/pymgl/blob/main/mbgl-core/maplibre-gl-native-core.cmake
* https://github.com/brendan-ward/pymgl/blob/main/mbgl-core/maplibre-gl-native-linux.cmake

This was originally adapted from the Linux and NodeJS CMake files in maplibre-gl-native, but simplified a bit for my specific use.  I could be mistaken, but I recall that the Linux build was more about bringing in Qt or GLFW; neither of which are needed for staticly rendering vector tiles.

See also the [development dependencies](https://github.com/brendan-ward/pymgl#developing-on-linux-ubuntu-2004-requires-the-following-binary-libraries) and [runtime dependencies](https://github.com/brendan-ward/pymgl#ubuntu-2004).

Side note: the [C++ wrapper](https://github.com/brendan-ward/pymgl/blob/main/src/map.cpp) wasn't strictly necessary, but provided the opportunity to better encapsulate logic and associated tests against the parts of `maplibre-gl-native` I was using, so that the actual Python bindings could be simpler and just bind against that wrapper.

**Comment by dwoznicki** [comment]
Thanks a bunch, folks. I've been really impressed by helpful this community is.

Using @acalcutt 's instructions, I managed to create a build. I can run the test suite like so.

```bash
cd build
xvfb-run -a ./mbgl-test-runner
```

A number of tests pass, though I eventually run into a segfault.

```
../test/api/query.test.cpp:206: Failure
Expected equality of these values:
  topClusterFeature.size()
    Which is: 0
  1u
    Which is: 1
Segmentation fault
```

Not sure if it's worth trying to solve.

I also understand that with `xvfb`, I'm using my CPU to execute GPU instructions (?). I imagine this is inefficient, so I'm hoping to install an external GPU to help with rendering time. Has anyone tried this? How did it go?

**Comment by dwoznicki** [comment]
Just leaving a note for myself as I go through the install process again. Here are some additional dependencies I had to install.

```bash
sudo apt install libjpeg-turbo8-dev libgl1-mesa-dev libgl1-mesa-glx libgl1-mesa-dri
```

**Comment by wipfli** [comment]
Thanks @dwoznicki for that note. I think it would be great if you could document this for others somewhere in a README or a CONTRIBUTING file or so. Would you like to make a pull request for this?

**Comment by dwoznicki** [comment]
@wipfli Mmm, yeah I'll give it a shot. I've installed maplibre-gl-native on multiple machines with multiple hardware configurations at this point, and I've somewhat lost track of what was necessary to install where. I think the instructions @acalcutt posted got me 90% of the way there though.
