### ISSUE TITLE
CPP Concurrent Crash (Grab has bugfix)

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-native#565]
## Summary

Since condition_variable::wait may call std::terminate, we replace it by pthread_cond.

## Grab has bugfix

The original author of this bug report is Grab. They have a bug fix and would like to upstream it to MapLibre GL Native.

**Comment by alanchenboy** [comment]
In fact, there is no crash at the thread pool, the report with condition_variable::wait is reported by firebase but firebase also reports the crash did not happen at the thread pool. 
<img width="1034" alt="Screenshot 2022-12-27 at 13 12 02" src="https://user-images.githubusercontent.com/5135389/209614680-dd2e9dee-2b39-4f6b-a5d0-40ddc76b8769.png">

Since it's an issue with firebase, so it does not depend on which waiting call you choose, using pthread_cond instead of condition_variable::wait does not improve the unknown crash.

So I support just closing this issue.

**Comment by ovivoda** [comment]
@alanchenboy Closing this as you suggested.
