### ISSUE TITLE
Wrong Padding Calculation (Grab has bugfix)

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-native#570]
## Summary

Update padding is direct pass value, but in some condition the padding in transform is not
valid(not same with the padding saving in GrabMap view). For example call setCamera with
parameter that calc from cameraThatFitsCoordinateBounds, setCamera must use a zero
padding, so the padding saving in transform is arbitrary , Hence only the padding delta is valid.
We change the way from sending padding value to sending padding delta.

## Grab has bugfix
The original author of this bug report is Grab. They have a bug fix and would like to upstream it to MapLibre GL Native.

**Comment by alanchenboy** [comment]
You may know.  Mapbox will fire a camera event when padding is changing, but our engineer doesn't want this message. so we just update the camera when the padding is changed which caused this issue.

Since MapLibre doesn't have this function (I mean just update the padding when the camera is moving) so this is not an issue for MapLibre.

**Comment by wipfli** [comment]
OK, should we close this issue?

**Comment by alanchenboy** [comment]
Yes I suggest just close it.
