### ISSUE TITLE
Labels getting clipped with some sources but not others

### ISSUE THREAD

**Issue by acalcutt** [maplibre/maplibre-gl-native#644]
Labels are getting clipped with some sources in tile mode, while others are not getting clipped

For an example, 

This map is using western-zone-latest.mbtiles from the example https://github.com/maptiler/tileserver-gl/issues/618#issuecomment-1328116302 which was made with  tilemaker. you can see the label is clipped.
https://tiles.wifidb.net/styles/western-zone/?raster#15/22.8167/72.7381
![image](https://user-images.githubusercontent.com/3792408/210261828-730b998c-b58b-47c3-9485-60967bf30dbe.png)

However this is the same style using a planetiler generated mbtiles file
https://tiles.wifidb.net/styles/bright/?raster#15/22.8167/72.7381
![image](https://user-images.githubusercontent.com/3792408/210262543-518540d2-3e50-40d6-83fb-4038180cec35.png)

What's the difference? Both these are rendered in tile mode. 

If I set tileserver to run in static mode, the second example clips text like the first example. The first example does not improve in static mode.

_Originally posted by @acalcutt in https://github.com/maplibre/maplibre-gl-native/issues/632#issuecomment-1369099484_

**Comment by tdcosta100** [comment]
Nice we can have a conversation not being offtopic hahaha. So, the real problem is the way the tiles are generated with TileMaker. It keeps only the features that are inside one particular tile. That means it doesn't include point features outside that tile. Planetiler seems to be smarter and include surrounding point features that go outside the tile, hence the non-clipping situation.

When I mentioned static, I mean the possibility of rendering the surrounding tiles, that is, with a margin that could include the point where the labels are rendered. This is my way to solve this my problem because I had my tiles generated with TileMaker. If you use static mode without a margin, labels will be clipped in some situations, probably worse than rendering with tile mode, like you demonstrated.

The Maplibre-GL-Native code already deals with this situation by rendering elements that go outside the tile borders. The only thing it needs is to have the tile data including points outside the tile. This is why TileMaker tiles are more prone to label clipping than Planetiler.

**Comment by acalcutt** [comment]
That makes sense. 

One of my idea to work around this in tileserver was to set the mode to static when the TileMargin option was set. similar to how I made it switch when using static tile mode  https://github.com/maptiler/tileserver-gl/pull/608 . That kind of makes it hard to have different sourced mbtiles though.

**Comment by tdcosta100** [comment]
For while, I think it's a good approach. The best solution would be have a better MBTiles source by TileMaker, or have parameters in Maplibre-GL-Native to make it load the surrounding tile data if the user wants to.

**Comment by acalcutt** [comment]
The thing I don't get is if this was at the tilemaker generation level, wouldn't that show in inspect when looking at the data?

If I look at https://tiles.wifidb.net/data/western-zone/#14/22.8167/72.7381 you can see the point and the full text
![image](https://user-images.githubusercontent.com/3792408/210287161-2c7f6601-d350-465f-9fa0-68dccc250001.png)

**Comment by tdcosta100** [comment]
Not in this case, because you are not fetching just one tile, you are fetching everything in this viewing window, that is, at least 4 tiles (maybe much more). You can check in DevTools's Network tab (Chrome, Opera, Firefox and Edge have it).

The problem with label clipping occurs only if the renderer didn't fetch any data yet in that region/zoom level. Tileserver-GL uses more than one renderer at a time, so if two separate renderers are rendering adjacent tiles, there is a bigger chance to have this problem occurring, because when renderer is requested, it tries to reuse data it has already fetched, so adjacent tile data (and label points) are present. If there are not surrounding tiles's data, and a point label is nearby, but outside of the tile of interest, then it will not be rendered in that tile, but when it comes to render the tile where it is, then it will be rendered, resulting in label clipping (because it is showing up in one tile but not in another, when it should appear in both).

**Comment by acalcutt** [comment]
I tested forcing tileserver to use a static mode renderer when TileMargin in this PR https://github.com/maptiler/tileserver-gl/pull/694/ and it does seem to work.

I was worried this would affect the other labels I fixed with tile mode in https://github.com/maplibre/maplibre-gl-native/issues/284 , but is seems the TileMargin of 10 was enough to keep those looking ok

**Comment by tdcosta100** [comment]
Yes, for every map you can find a reasonable margin amount. I went crazy and added a 256 tile margin HAHAHA. Insane amount of extra rendering (768x768 for every 256x256 tile), but never faced label problems again. Of course I really prefer to have data fetched in a better way than rendering data like that.
