### ISSUE TITLE
Evaluate using DocC for iOS documentation

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-gl-native#676]
The Apple recommended way to provide documentation is [DocC](https://developer.apple.com/documentation/docc).

Worth taking a look at I think, especially since the iOS docs are in need of a refresh anyway.

**Comment by birkskyum** [comment]
We currently use the [Jazzy](https://github.com/realm/jazzy) pipeline for iOS docs generation.

A few years ago Apple released [DocC](https://developer.apple.com/documentation/docc) as the officially recommended docs compiler. Streamlining docs in the ecosystem makes resources easier to consume for Apple developers. DocC initially lacked support for GitHub Pages, which is how we currently deploy our docs, but [it's supported now](https://apple.github.io/swift-docc-plugin/documentation/swiftdoccplugin/publishing-to-github-pages/). DocC initially only held support for Swift, but ObjC (which is the majority of our iOS SDK) has been [added since XCode 14](https://developer.apple.com/forums/thread/681800).
