### ISSUE TITLE
Does MapLibre still not support 3D terrain？

### ISSUE THREAD

**Issue by jayhuang861019** [maplibre/maplibre-gl-native#838]
i set a RasterDemSource and a HillshadeLayer and add them to the map but it did not work,Does MapLibre still not support 3D terrain？

**Comment by louwers** [comment]
MapLibre GL JS does, MapLibre GL Native does not at this point. See #252

**Comment by jayhuang861019** [comment]
Will it be supported this year or in the future?

**Comment by CodeK1988** [comment]
Will it be supported this year or in the future?

**Comment by louwers** [comment]
Parity with MapLibre JS is one of the goals of the project and it may be implemented in 2024. 

Please leave an upvote on the issue I linked to indicate your interest. Asking when something is done is considered bad etiquette because it doens't add to the discussion and notifies subscribers to an issue. :)
