### ISSUE TITLE
Remove `Pass` and `PassRefPtr` in favor of `[[nodiscard]]`

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-gl-native#875]
https://github.com/maplibre/maplibre-gl-native/blob/682f5e895282e47de1eea665d17e4e6c6cb9335f/include/mbgl/util/pass_types.hpp

If I understand it correctly `Pass` and `PassRefPtr` can be replaced with the [`[[nodiscard]]`](https://en.cppreference.com/w/cpp/language/attributes/nodiscard) attribute.

This would be a breaking change since it is part of the public interface.

**Comment by ntadej** [comment]
Sounds correct.

**Comment by rpitre-wetdog** [comment]
Looking at the usage of PassRefPtr, the return value is always put in a shared_ptr via the Pass operator(). So yes we can get rid of Pass and PassRefPtr by changing all the methods that returns a PassRefPtr to just return a shared_ptr. If we just do that the behavior would be like before. Now we could tag all those methods  with [[[nodiscard]]] so that we would get  a compiler warning if the caller ignores the return value. My question is do we want to support both cases ?

**Comment by louwers** [comment]
@rpitre-wetdog If you are asking if we can break the API, then yes. We don't do stable releases of the core (or releases at all).

**Comment by ntadej** [comment]
I think we should still make a changelog entry as we may tag separate core releases in the future, but it's fine to make a breaking change now.

**Comment by ovivoda** [comment]
indeed. @rpitre-wetdog please document this into the changelog as well.
